name = "EChartsLight"
uuid = "227973c0-0bd2-43ce-818e-253b1f0b56ac"
version = "0.1.0"
authors = ["Anand Bisen <asbisen@icloud.com>"]

[deps]
Cobweb = "ec354790-cf28-43e8-bb59-b484409b7bad"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ECharts_jll = "ffd69456-1935-58d2-abba-ba12e8909167"
EasyConfig = "acab07b0-f158-46d4-8913-50acef6d41fe"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Cobweb = "0.7.2"
Dates = "1.11.0"
Distributions = "0.25.122"
Downloads = "1.7.0"
ECharts_jll = "6.0.0"
EasyConfig = "0.1.16"
JSON3 = "1.14.3"
Random = "1.11.0"
Test = "1.11.0"
