name = "EChartsLight"
uuid = "227973c0-0bd2-43ce-818e-253b1f0b56ac"
version = "0.1.0"
authors = ["Anand Bisen <asbisen@icloud.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cobweb = "ec354790-cf28-43e8-bb59-b484409b7bad"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
EasyConfig = "acab07b0-f158-46d4-8913-50acef6d41fe"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CSV = "0.10.15"
Cobweb = "0.7.2"
DBInterface = "2.6.1"
DataFrames = "1.8.1"
Dates = "1.11.0"
DuckDB = "1.4.1"
EasyConfig = "0.1.16"
HTTP = "1.10.19"
JSON3 = "1.14.3"
Markdown = "1.11.0"
Random = "1.11.0"
Test = "1.11.0"
UUIDs = "1.11.0"
