[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EChartsLight = "227973c0-0bd2-43ce-818e-253b1f0b56ac"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"

[sources]
EChartsLight = {rev = "main", url = "git@github.com:asbisen/EChartsLight.jl.git"}
